AskForAnswer/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AskForAnswer.Data;
using AskForAnswer.Models;
using Microsoft.AspNetCore.Authorization;

namespace AskForAnswer.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<QuestionsController> _logger;


        public QuestionsController(ApplicationDbContext context, ILogger<QuestionsController> logger)
        {
	        _context = context;
	        _logger = logger;
        }

        // GET: Questions
        public async Task<IActionResult> Index(int? pageNumber)
        {


            var applicationDbContext = _context.Questions
                                                                                    .Include(q => q.User)
                                                                                    .Include(c=> c.Answers);

            int pageSize = 3;

			return View(await PaginatedList<Question>.CreateAsync(applicationDbContext, pageNumber ?? 1, pageSize));
        }

		// GET: Questions/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				_logger.LogInformation("Details view requested with a null ID.");
				return NotFound();
			}

			var question = await _context.Questions
				.Include(q => q.Answers)
				.ThenInclude(a => a.User) // Assuming each answer has a User associated with it
				.Include(q => q.User)
				.AsNoTracking() // Good practice for read-only scenarios
				.FirstOrDefaultAsync(m => m.Id == id);

			if (question == null)
			{
				_logger.LogInformation($"No question found with ID {id}.");
				return NotFound();
			}

			return View(question);
		}


        // GET: Questions/Create
        [Authorize]
		public IActionResult Create()
        {
            
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        
        [HttpPost]
        [Authorize]
		[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,IdentityUserId")] Question question)
        {
            if (ModelState.IsValid)
            {
                _context.Add(question);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(question);
        }

		// GET: Questions/Edit/5
		[Authorize]
		public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions.FindAsync(id);

            if (question.IdentityUserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", question.IdentityUserId);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
		[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,IdentityUserId")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", question.IdentityUserId);
            return View(question);
        }

		// GET: Questions/Delete/5
		[Authorize]
		public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .Include(q => q.User)
                .FirstOrDefaultAsync(m => m.Id == id);
			
            if (question.IdentityUserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
			{
				return NotFound();
			}

			return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
		[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Questions.FindAsync(id);
            if (question != null)
            {
                _context.Questions.Remove(question);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.Id == id);
		}

        // POST: Answers
        // To protect from overposting attacks, enable the specific properties you want to bind to.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
		public async Task<IActionResult> AddAnswer([Bind("Id,Content,QuestionId,IdentityUserId")] Answer answer)
        {
	        if (ModelState.IsValid)
	        {
		        _context.Add(answer);
		        await _context.SaveChangesAsync();
	        }

	        var questions = _context.Questions
				.Include(a => a.Answers)
		        .ThenInclude(a => a.User)
		        .FirstOrDefault(q=>q.Id == answer.QuestionId);

	        return View("Details",questions);
        }
	}
}

AskForAnswer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AskForAnswer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AskForAnswer.styles.css" asp-append-version="true" />

    <style>
        body {
            font-family: 'Arial', sans-serif;
        }

        .navbar-custom {
            background-color: #004d99; /* Customize with your color */
        }

            .navbar-custom .navbar-brand, .navbar-custom .nav-link {
                color: #fff;
            }

        .footer-custom {
            background-color: #f2f2f2;
        }

        .card-custom {
            border-left: 4px solid #004d99; /* Customize with your color */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-custom sticky-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Questions" asp-action="Index">AskForAnswer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Questions" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Questions" asp-action="Create">Submit a question</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
	                        <li class="nav-item dropdown">
		                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			                        Admin
		                        </a>
		                        <ul class="dropdown-menu">
			                        <li><a class="dropdown-item" asp-controller="Admin" asp-action="ListUsers">Manage Users</a></li>
			                        <li><a class="dropdown-item" asp-controller="Admin" asp-action="ListQuestions">Manage Questions</a></li>
		                        </ul>
	                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer-custom text-muted">
        <div class="container">
            &copy; 2023 - AskForAnswer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>